//! Golden-vector tests that pin the EXI profile ISO 15118 uses.
//!
//! "Which EXI options does ISO 15118 use?" is the single question this whole
//! codebase rests on, and the answer is not in any XSD — it is out-of-band
//! knowledge that implementations either share or silently disagree about.
//! This file settles it against bytes produced by other people's code.
//!
//! The vectors below are ISO 15118-20 `SessionStop` messages taken from the
//! test suite of [EVerest/libiso15118], an independent C++ implementation whose
//! codec is generated by `cbexigen`. They are reproduced byte for byte by the
//! EXI reference implementation (`exificient` 1.0.7) when — and only when — it
//! is configured with schema-informed grammars, bit-packed alignment, and
//! **default fidelity options, meaning `strict = false`**. Under `strict =
//! true` the same message encodes to different bytes and a different length.
//!
//! [EVerest/libiso15118]: https://github.com/EVerest/libiso15118
//!
//! Each vector is checked twice, and the two checks answer different questions.
//!
//! Walking it **event by event** with hand-written widths proves the *grammar
//! arithmetic*: every width asserted here was derived from
//! `V2G_CI_CommonMessages.xsd` and `V2G_CI_CommonTypes.xsd` before the bytes
//! were looked at, so a passing walk means the derivation and the bytes agree.
//!
//! Decoding it through the **generated codec** proves that the generated code
//! implements that arithmetic. Without it the walk could be right about the
//! grammar while the codec shipped something else; without the walk, a bug
//! shared by the derivation and the generator would go unnoticed.

use iso15118::exi::{Decoder, Encoder, ExiError, Header, Lengths};

/// `SessionStopReq`, session `3D4CBF93374ED89B`, timestamp 1725456343,
/// `ChargingSession = Terminate`.
const SESSION_STOP_REQ: &[u8] = &[
    0x80, 0x94, 0x04, 0x1e, 0xa6, 0x5f, 0xc9, 0x9b, 0xa7, 0x6c, 0x4d, 0x8d, 0x7b, 0xfe, 0x1b, 0x60,
    0x62, 0x28,
];

/// `SessionStopRes`, same header, `ResponseCode = OK`.
const SESSION_STOP_RES: &[u8] = &[
    0x80, 0x98, 0x04, 0x1e, 0xa6, 0x5f, 0xc9, 0x9b, 0xa7, 0x6c, 0x4d, 0x8d, 0x7b, 0xfe, 0x1b, 0x60,
    0x62, 0x00, 0x00,
];

const SESSION_ID: &[u8] = &[0x3D, 0x4C, 0xBF, 0x93, 0x37, 0x4E, 0xD8, 0x9B];
const TIMESTAMP: u64 = 1_725_456_343;

// --- Grammar constants, derived from the schemas ---------------------------
//
// The document grammar ranges over every global element in the schema *set*:
// 28 from CommonMessages, 2 from CommonTypes, 24 from xmldsig-core — 54 in all,
// sorted by local name then namespace. Non-strict adds a generic `SE(*)`
// production, making 55 alternatives, which needs six bits. `iso15118-codegen`
// derives the same table straight from the XSDs; see its `--check` mode.
const W_ROOT: u32 = 6;
const EC_SESSION_STOP_REQ: u64 = 37;
const EC_SESSION_STOP_RES: u64 = 38;

/// A grammar state offering one declared production. Under non-strict rules the
/// second-level productions make it a two-way choice, hence one bit — this is
/// the constant that would be *zero* if ISO 15118 used strict mode.
const W_ONE: u32 = 1;
/// A state offering two declared productions.
const W_TWO: u32 = 2;
/// A state offering three declared productions.
const W_THREE: u32 = 2;

/// `chargingSessionType`: Pause, Terminate, `ServiceRenegotiation`.
const W_CHARGING_SESSION: u32 = 2;
/// `Terminate` is the second value in schema document order.
const EC_TERMINATE: u64 = 1;
/// `responseCodeType`: forty values.
const W_RESPONSE_CODE: u32 = 6;
/// `OK` is the first.
const EC_OK: u64 = 0;

/// Reads the `Header` element the two messages share: `SessionID` then
/// `TimeStamp`, with `Signature` absent.
fn expect_message_header(d: &mut Decoder<'_>) {
    assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(Header)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(SessionID)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(SessionID)");
    assert_eq!(d.binary(Lengths::max(8)).unwrap(), SESSION_ID);
    assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(SessionID)");

    assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(TimeStamp)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(TimeStamp)");
    assert_eq!(d.uint().unwrap(), TIMESTAMP);
    assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(TimeStamp)");

    // Signature is optional, so this state offers SE(Signature) or EE.
    assert_eq!(d.event(W_TWO).unwrap(), 1, "EE(Header), no Signature");
}

fn write_message_header(e: &mut Encoder<'_>) {
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.binary(SESSION_ID, Lengths::max(8)).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.uint(TIMESTAMP).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(1, W_TWO).unwrap();
}

#[test]
fn iso20_session_stop_req_decodes_event_by_event() {
    let mut d = Decoder::new(SESSION_STOP_REQ);
    assert_eq!(d.read_header().unwrap(), Header::ISO15118);
    assert_eq!(d.event(W_ROOT).unwrap(), EC_SESSION_STOP_REQ, "SE(SessionStopReq)");

    expect_message_header(&mut d);

    assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(ChargingSession)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(ChargingSession)");
    assert_eq!(d.nbit(W_CHARGING_SESSION).unwrap(), EC_TERMINATE);
    assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(ChargingSession)");

    // EVTerminationCode and EVTerminationExplanation are both optional, so the
    // final state is a three-way choice; 2 is EE.
    assert_eq!(d.event(W_THREE).unwrap(), 2, "EE(SessionStopReq)");

    d.finish().expect("the document ends exactly where the grammar says it does");
}

#[test]
fn iso20_session_stop_req_reencodes_byte_for_byte() {
    let mut buf = [0u8; 64];
    let mut e = Encoder::new(&mut buf);
    e.write_header(Header::ISO15118).unwrap();
    e.event(EC_SESSION_STOP_REQ, W_ROOT).unwrap();
    write_message_header(&mut e);
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.nbit(EC_TERMINATE, W_CHARGING_SESSION).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(2, W_THREE).unwrap();
    let n = e.finish().unwrap();

    assert_eq!(&buf[..n], SESSION_STOP_REQ);
}

#[test]
fn iso20_session_stop_res_decodes_event_by_event() {
    let mut d = Decoder::new(SESSION_STOP_RES);
    assert_eq!(d.read_header().unwrap(), Header::ISO15118);
    assert_eq!(d.event(W_ROOT).unwrap(), EC_SESSION_STOP_RES, "SE(SessionStopRes)");

    expect_message_header(&mut d);

    assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(ResponseCode)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(ResponseCode)");
    assert_eq!(d.nbit(W_RESPONSE_CODE).unwrap(), EC_OK);
    assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(ResponseCode)");
    assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(SessionStopRes)");

    d.finish().unwrap();
}

#[test]
fn iso20_session_stop_res_reencodes_byte_for_byte() {
    let mut buf = [0u8; 64];
    let mut e = Encoder::new(&mut buf);
    e.write_header(Header::ISO15118).unwrap();
    e.event(EC_SESSION_STOP_RES, W_ROOT).unwrap();
    write_message_header(&mut e);
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.nbit(EC_OK, W_RESPONSE_CODE).unwrap();
    e.event(0, W_ONE).unwrap();
    e.event(0, W_ONE).unwrap();
    let n = e.finish().unwrap();

    assert_eq!(&buf[..n], SESSION_STOP_RES);
}

/// The generated ISO 15118-20 codec, against the same bytes.
///
/// The walk above says the grammar is right; this says the code that was
/// generated from it agrees, end to end, without a hand-written width anywhere
/// in the path.
#[cfg(feature = "iso20-common")]
#[test]
fn iso20_vectors_round_trip_through_the_generated_codec() {
    use iso15118::exi::ExiDocument;
    use iso15118::iso20::messages::{ChargingSession, Document};

    let req = Document::from_bytes(SESSION_STOP_REQ).expect("decode SessionStopReq");
    let Document::SessionStopReq(stop) = &req else { panic!("wrong message: {}", req.name()) };
    assert_eq!(stop.header.session_id, SESSION_ID);
    assert_eq!(stop.header.time_stamp, 1_725_456_343);
    assert_eq!(stop.charging_session, ChargingSession::Terminate);
    assert_eq!(req.to_vec().expect("re-encode"), SESSION_STOP_REQ);

    let res = Document::from_bytes(SESSION_STOP_RES).expect("decode SessionStopRes");
    let Document::SessionStopRes(done) = &res else { panic!("wrong message: {}", res.name()) };
    assert_eq!(done.header.session_id, SESSION_ID);
    assert!(done.response_code.is_ok());
    assert_eq!(res.to_vec().expect("re-encode"), SESSION_STOP_RES);
}

#[test]
fn the_request_and_response_differ_only_in_the_root_event_code() {
    // 37 and 38 are adjacent because `SessionStopReq` sorts immediately before
    // `SessionStopRes`. If the global-element ordering were computed any other
    // way — by namespace first, say, or in schema order — these two would not
    // be neighbours and neither vector would decode.
    assert_eq!(EC_SESSION_STOP_RES, EC_SESSION_STOP_REQ + 1);
    assert_eq!(SESSION_STOP_REQ[1] >> 2, u8::try_from(EC_SESSION_STOP_REQ).unwrap());
    assert_eq!(SESSION_STOP_RES[1] >> 2, u8::try_from(EC_SESSION_STOP_RES).unwrap());
}

#[test]
fn strict_mode_widths_would_not_decode_these_vectors() {
    // Under strict fidelity every `W_ONE` above would be zero bits. Walking the
    // same vector with those widths must fail — either by running off the end,
    // by reading a nonsensical value, or by leaving data unconsumed. This is
    // the negative half of the profile claim: it is not that non-strict merely
    // works, it is that strict cannot.
    let mut d = Decoder::new(SESSION_STOP_REQ);
    d.read_header().unwrap();
    assert_eq!(d.event(W_ROOT).unwrap(), EC_SESSION_STOP_REQ);

    // strict: SE(Header) and SE(SessionID) and CH cost nothing.
    let session_id = d.binary(Lengths::max(8));
    let mismatch = match session_id {
        Err(_) => true,
        Ok(bytes) => bytes != SESSION_ID,
    };
    assert!(mismatch, "strict-mode widths must not reproduce the session id");
}

#[test]
fn a_truncated_vector_is_rejected_rather_than_half_decoded() {
    for n in 1..SESSION_STOP_REQ.len() {
        let mut d = Decoder::new(&SESSION_STOP_REQ[..n]);
        let outcome = (|| -> Result<(), ExiError> {
            d.read_header()?;
            if d.event(W_ROOT)? != EC_SESSION_STOP_REQ {
                return Err(ExiError::UnknownEventCode);
            }
            d.event(W_ONE)?;
            d.event(W_ONE)?;
            d.event(W_ONE)?;
            d.binary(Lengths::max(8))?;
            d.event(W_ONE)?;
            d.event(W_ONE)?;
            d.event(W_ONE)?;
            d.uint()?;
            d.event(W_ONE)?;
            d.event(W_TWO)?;
            d.event(W_ONE)?;
            d.event(W_ONE)?;
            d.nbit(W_CHARGING_SESSION)?;
            d.event(W_ONE)?;
            d.event(W_THREE)?;
            d.finish()
        })();
        assert!(outcome.is_err(), "{n} bytes of an 18-byte document must not parse");
    }
}

/// ISO 15118-2 vectors.
///
/// Produced by `exificient` 1.0.7 from `V2G_CI_MsgDef.xsd` under the same
/// profile as the ISO 15118-20 vectors above. They exercise two things the -20
/// vectors do not:
///
/// * a **seven-bit** document event code — the -2 schema set declares eighty
///   global elements, so `V2G_Message` sits at code 76 of 81 alternatives;
/// * a **substitution group** — every -2 message is a branch of the choice that
///   `BodyType` expands `<element ref="BodyElement"/>` into. The abstract head
///   `BodyElement` occupies a branch of its own, which is why `SessionSetupReq`
///   is code 29 and not 28.
mod iso2 {
    use super::{Decoder, Encoder, Header, Lengths};

    /// `V2G_Message` carrying `SessionSetupReq` with `EVCCID = 0011223344AA`.
    const SESSION_SETUP_REQ: &[u8] = &[
        0x80, 0x98, 0x02, 0x0f, 0x53, 0x2f, 0xe4, 0xcd, 0xd3, 0xb6, 0x26, 0xd1, 0xd0, 0x18, 0x00,
        0x44, 0x88, 0xcd, 0x12, 0xa8, 0x00,
    ];

    /// `V2G_Message` carrying `SessionSetupRes`: `OK_NewSessionEstablished`,
    /// `EVSEID = DE*ABC*E00001`, `EVSETimeStamp = 1725456343`.
    const SESSION_SETUP_RES: &[u8] = &[
        0x80, 0x98, 0x02, 0x0f, 0x53, 0x2f, 0xe4, 0xcd, 0xd3, 0xb6, 0x26, 0xd1, 0xe0, 0x20, 0x3d,
        0x11, 0x14, 0xa9, 0x05, 0x09, 0x0c, 0xa9, 0x14, 0xc0, 0xc0, 0xc0, 0xc0, 0xc4, 0x1a, 0xf7,
        0xfc, 0x36, 0xc0, 0xc0,
    ];

    const SESSION_ID: &[u8] = &[0x3D, 0x4C, 0xBF, 0x93, 0x37, 0x4E, 0xD8, 0x9B];

    /// Eighty global elements plus `SE(*)`.
    const W_ROOT: u32 = 7;
    const EC_V2G_MESSAGE: u64 = 76;
    /// Thirty-five substitution branches plus `EE`.
    const W_BODY: u32 = 6;
    const EC_SESSION_SETUP_REQ: u64 = 29;
    const EC_SESSION_SETUP_RES: u64 = 30;
    /// `responseCodeType` has **twenty-six** values, so five bits — not the six
    /// a glance at the schema suggests, because the enumeration is shorter than
    /// it looks. Counting it by hand got this wrong; `iso15118-codegen` parses
    /// the facet and gets it right, which is the argument for the tool.
    const W_RESPONSE_CODE: u32 = 5;
    /// Enumeration indices follow schema document order, not lexicographic
    /// order: `OK` is 0, `OK_NewSessionEstablished` is 1.
    const EC_OK_NEW_SESSION: u64 = 1;

    const W_ONE: u32 = 1;
    const W_TWO: u32 = 2;
    /// `MessageHeaderType` offers `Notification`, `Signature` or `EE`.
    const W_HEADER_END: u32 = 2;
    const EC_HEADER_END: u64 = 2;

    /// Reads `V2G_Message`'s header: a session id and nothing else.
    fn expect_header(d: &mut Decoder<'_>) {
        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(Header)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(SessionID)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(SessionID)");
        assert_eq!(d.binary(Lengths::max(8)).unwrap(), SESSION_ID);
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(SessionID)");
        assert_eq!(d.event(W_HEADER_END).unwrap(), EC_HEADER_END, "EE(Header)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(Body)");
    }

    fn write_header(e: &mut Encoder<'_>) {
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.binary(SESSION_ID, Lengths::max(8)).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(EC_HEADER_END, W_HEADER_END).unwrap();
        e.event(0, W_ONE).unwrap();
    }

    #[test]
    fn session_setup_req_decodes_event_by_event() {
        let mut d = Decoder::new(SESSION_SETUP_REQ);
        assert_eq!(d.read_header().unwrap(), Header::ISO15118);
        assert_eq!(d.event(W_ROOT).unwrap(), EC_V2G_MESSAGE, "SE(V2G_Message)");
        expect_header(&mut d);
        assert_eq!(d.event(W_BODY).unwrap(), EC_SESSION_SETUP_REQ, "the substitution branch");

        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(EVCCID)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(EVCCID)");
        assert_eq!(d.binary(Lengths::max(6)).unwrap(), &[0x00, 0x11, 0x22, 0x33, 0x44, 0xAA]);
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(EVCCID)");

        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(SessionSetupReq)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(Body)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(V2G_Message)");
        d.finish().unwrap();
    }

    #[test]
    fn session_setup_req_reencodes_byte_for_byte() {
        let mut buf = [0u8; 64];
        let mut e = Encoder::new(&mut buf);
        e.write_header(Header::ISO15118).unwrap();
        e.event(EC_V2G_MESSAGE, W_ROOT).unwrap();
        write_header(&mut e);
        e.event(EC_SESSION_SETUP_REQ, W_BODY).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.binary(&[0x00, 0x11, 0x22, 0x33, 0x44, 0xAA], Lengths::max(6)).unwrap();
        for _ in 0..4 {
            e.event(0, W_ONE).unwrap();
        }
        let n = e.finish().unwrap();
        assert_eq!(&buf[..n], SESSION_SETUP_REQ);
    }

    #[test]
    fn session_setup_res_decodes_event_by_event() {
        use iso15118::exi::ValueCtx;

        let mut d = Decoder::new(SESSION_SETUP_RES);
        assert_eq!(d.read_header().unwrap(), Header::ISO15118);
        assert_eq!(d.event(W_ROOT).unwrap(), EC_V2G_MESSAGE);
        expect_header(&mut d);
        assert_eq!(d.event(W_BODY).unwrap(), EC_SESSION_SETUP_RES);

        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(ResponseCode)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(ResponseCode)");
        assert_eq!(d.nbit(W_RESPONSE_CODE).unwrap(), EC_OK_NEW_SESSION);
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(ResponseCode)");

        assert_eq!(d.event(W_ONE).unwrap(), 0, "SE(EVSEID)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(EVSEID)");
        // A string value, so it goes through the string table: first sighting,
        // coded literally with a length offset by two.
        assert_eq!(d.string(ValueCtx(0), Lengths::max(37)).unwrap(), "DE*ABC*E00001");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(EVSEID)");

        // EVSETimeStamp is optional: SE or EE.
        assert_eq!(d.event(W_TWO).unwrap(), 0, "SE(EVSETimeStamp)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "CH(EVSETimeStamp)");
        // xs:long is signed, so this is an EXI Integer, not an Unsigned Integer.
        assert_eq!(d.int().unwrap(), 1_725_456_343);
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(EVSETimeStamp)");

        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(SessionSetupRes)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(Body)");
        assert_eq!(d.event(W_ONE).unwrap(), 0, "EE(V2G_Message)");
        d.finish().unwrap();
    }

    #[test]
    fn session_setup_res_reencodes_byte_for_byte() {
        use iso15118::exi::ValueCtx;

        let mut buf = [0u8; 64];
        let mut e = Encoder::new(&mut buf);
        e.write_header(Header::ISO15118).unwrap();
        e.event(EC_V2G_MESSAGE, W_ROOT).unwrap();
        write_header(&mut e);
        e.event(EC_SESSION_SETUP_RES, W_BODY).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.nbit(EC_OK_NEW_SESSION, W_RESPONSE_CODE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_ONE).unwrap();
        e.string(ValueCtx(0), "DE*ABC*E00001", Lengths::max(37)).unwrap();
        e.event(0, W_ONE).unwrap();
        e.event(0, W_TWO).unwrap();
        e.event(0, W_ONE).unwrap();
        e.int(1_725_456_343).unwrap();
        for _ in 0..4 {
            e.event(0, W_ONE).unwrap();
        }
        let n = e.finish().unwrap();
        assert_eq!(&buf[..n], SESSION_SETUP_RES);
    }

    /// The generated ISO 15118-2 codec, against the same bytes.
    #[cfg(feature = "iso2")]
    #[test]
    fn iso2_vectors_round_trip_through_the_generated_codec() {
        use iso15118::exi::ExiDocument;
        use iso15118::iso2::{BodyChoice, Document, ResponseCode};

        let req = Document::from_bytes(SESSION_SETUP_REQ).expect("decode SessionSetupReq");
        let Document::V2GMessage(msg) = &req else { panic!("wrong root: {}", req.name()) };
        assert_eq!(msg.header.session_id, SESSION_ID);
        let Some(BodyChoice::SessionSetupReq(setup)) = &msg.body.choice else {
            panic!("wrong body")
        };
        assert_eq!(setup.evcc_id, [0x00, 0x11, 0x22, 0x33, 0x44, 0xAA]);
        assert_eq!(req.to_vec().expect("re-encode"), SESSION_SETUP_REQ);

        let res = Document::from_bytes(SESSION_SETUP_RES).expect("decode SessionSetupRes");
        let Document::V2GMessage(msg) = &res else { panic!("wrong root: {}", res.name()) };
        let Some(BodyChoice::SessionSetupRes(setup)) = &msg.body.choice else {
            panic!("wrong body")
        };
        assert_eq!(setup.response_code, ResponseCode::OKNewSessionEstablished);
        assert_eq!(setup.evse_id, "DE*ABC*E00001");
        assert_eq!(setup.evse_time_stamp, Some(1_725_456_343));
        assert_eq!(res.to_vec().expect("re-encode"), SESSION_SETUP_RES);
    }

    #[test]
    fn the_abstract_substitution_head_occupies_a_branch() {
        // If `BodyElement` — which is `abstract="true"` and can never appear in
        // an instance — were left out of the choice, every message after it
        // alphabetically would shift down one code and these vectors would
        // decode as the wrong message type.
        assert_eq!(EC_SESSION_SETUP_RES, EC_SESSION_SETUP_REQ + 1);
        assert_eq!(SESSION_SETUP_REQ[1] >> 1, u8::try_from(EC_V2G_MESSAGE).unwrap());
    }
}
